Compute:
    "jobs"      : [16]
    "cpus"      : [16]
    "ram"       : ["492GB"]
    "time"      : ["06:00:00"]
    "account"   : ["bsmfc"]
    "partition" : ["large"]

Aggregate:
    "cpus"      : [1]
    "ram"       : ["492GB"]
    "time"      : ["00:30:00"]
    "account"   : ["bsmfc"]
    "partition" : ["large"]
