Compute:
    "jobs"      : [940]
    "cpus"      : [1]
    "ram"       : ["6GB"]
    "time"      : ["01:00:00"]
    "account"   : ["bsmfc"]
    "partition" : ["batch"]

Aggregate:
    "cpus"      : [1]
    "ram"       : ["16GB"]
    "time"      : ["00:30:00"]
    "account"   : ["bsmfc"]
    "partition" : ["batch"]
